name: defect
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - setuptools>=41.0.1
  - flake8>=3.7.9
  - matplotlib>=3.1.1
  - pytorch>=1.8.0
  - torchvision>=0.9.0
  - numpy>=1.16.4
  - scipy>=1.3.0
  - scikit-learn>=0.22.1
  - scikit-image>=0.16.2
  - networkx>=2.5
  - progressbar2>=3.38.0
  - pip
  - pip:
      - gdown>=3.8.1
      - opencv-python>=4.1.0
      - mendeleev<=0.6.1
      - gpytorch>=1.4.0,<1.7.0
      - atomai